defaults:
  - _self_
  - model: baseline
  - preprocessing: transform_strategy/encode_not_ordered
#  - base_config FIXME need help


random_state: 1
relative_path_to_data_storage: data/raw/heart_cleveland_upload.csv
relative_path_to_reports_storage: reports/EDA.html
