stages:
  download data:
    cmd: mlops_homework_download_dataset
    deps:
      - mlops_homework/data/load_dataset.py
    outs:
      - data/raw/heart_cleveland_upload.csv
  process data:
    cmd: mlops_homework_process_dataset
    deps:
      - mlops_homework/data/build_features.py
      - data/raw/heart_cleveland_upload.csv
    outs:
      - data/processed/heart_cleveland_upload.csv
