name: Python package

on:
  - pull_request
  - workflow_dispatch

jobs:
  test-all:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: mlflow
          POSTGRES_PASSWORD: mlflow
          POSTGRES_USER: mlflow
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd ml_project
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          cd ml_project
          flake8 . --count --max-line-length=120 --show-source --statistics --ignore=F403,F405,W605,F811
      - name: Test with pytest
        run: |
          export KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }}
          export KAGGLE_KEY=${{ secrets.KAGGLE_KEY }}
          export MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}
          cd ml_project
          dvc exp run
          pytest